package it.clevercom.echo.hibernate.sso.postgresql.entity;
// Generated 17-feb-2017 17.36.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Application implements java.io.Serializable {

	private long idapplication;
	private String code;
	private String description;
	private String url;
	private Date created;
	private Date updated;
	private String updateuser;
	private boolean active;
	private Set<LoginApplication> loginApplications = new HashSet<LoginApplication>(0);

	public Application() {
	}

	public Application(long idapplication, String code, String description, Date created, Date updated,
			String updateuser, boolean active) {
		this.idapplication = idapplication;
		this.code = code;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
	}

	public Application(long idapplication, String code, String description, String url, Date created, Date updated,
			String updateuser, boolean active, Set<LoginApplication> loginApplications) {
		this.idapplication = idapplication;
		this.code = code;
		this.description = description;
		this.url = url;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
		this.loginApplications = loginApplications;
	}

	@Id

	@Column(name = "idapplication", unique = true, nullable = false)
	public long getIdapplication() {
		return this.idapplication;
	}

	public void setIdapplication(long idapplication) {
		this.idapplication = idapplication;
	}

	@Column(name = "code", unique = true, nullable = false, length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "updateuser", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
	public Set<LoginApplication> getLoginApplications() {
		return this.loginApplications;
	}

	public void setLoginApplications(Set<LoginApplication> loginApplications) {
		this.loginApplications = loginApplications;
	}

}
