package it.clevercom.echo.hibernate.sso.postgresql.entity;
// Generated 17-feb-2017 17.36.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Login implements java.io.Serializable {

	private long idlogin;
	private String username;
	private String password;
	private String email;
	private Date lastpasswordreset;
	private Short adlogon;
	private Date created;
	private Date updated;
	private String updateuser;
	private boolean active;
	private Set<LoginApplication> loginApplications = new HashSet<LoginApplication>(0);

	public Login() {
	}

	public Login(long idlogin, String username, String password, String email, Date lastpasswordreset, Date created,
			Date updated, String updateuser, boolean active) {
		this.idlogin = idlogin;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastpasswordreset = lastpasswordreset;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
	}

	public Login(long idlogin, String username, String password, String email, Date lastpasswordreset, Short adlogon,
			Date created, Date updated, String updateuser, boolean active, Set<LoginApplication> loginApplications) {
		this.idlogin = idlogin;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastpasswordreset = lastpasswordreset;
		this.adlogon = adlogon;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
		this.loginApplications = loginApplications;
	}

	@Id

	@Column(name = "idlogin", unique = true, nullable = false)
	public long getIdlogin() {
		return this.idlogin;
	}

	public void setIdlogin(long idlogin) {
		this.idlogin = idlogin;
	}

	@Column(name = "username", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastpasswordreset", nullable = false, length = 29)
	public Date getLastpasswordreset() {
		return this.lastpasswordreset;
	}

	public void setLastpasswordreset(Date lastpasswordreset) {
		this.lastpasswordreset = lastpasswordreset;
	}

	@Column(name = "adlogon")
	public Short getAdlogon() {
		return this.adlogon;
	}

	public void setAdlogon(Short adlogon) {
		this.adlogon = adlogon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "updateuser", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "login")
	public Set<LoginApplication> getLoginApplications() {
		return this.loginApplications;
	}

	public void setLoginApplications(Set<LoginApplication> loginApplications) {
		this.loginApplications = loginApplications;
	}

}
