package it.clevercom.echo.rd.model.entity;
// Generated 28-feb-2017 10.00.08 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BurnRobot generated by hbm2java
 */
@Entity
@Table(name = "burn_robot")
public class BurnRobot implements java.io.Serializable {

	private long idburnrobot;
	private OrganizationUnit organizationUnit;
	private String name;
	private String hostname;
	private String ipaddress;
	private String uri;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;

	public BurnRobot() {
	}

	public BurnRobot(long idburnrobot, String name, Date created, Date updated, String userupdate, boolean active) {
		this.idburnrobot = idburnrobot;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public BurnRobot(long idburnrobot, OrganizationUnit organizationUnit, String name, String hostname,
			String ipaddress, String uri, Date created, Date updated, String userupdate, boolean active) {
		this.idburnrobot = idburnrobot;
		this.organizationUnit = organizationUnit;
		this.name = name;
		this.hostname = hostname;
		this.ipaddress = ipaddress;
		this.uri = uri;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "idburnrobot", unique = true, nullable = false)
	public long getIdburnrobot() {
		return this.idburnrobot;
	}

	public void setIdburnrobot(long idburnrobot) {
		this.idburnrobot = idburnrobot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idorganizationunit")
	public OrganizationUnit getOrganizationUnit() {
		return this.organizationUnit;
	}

	public void setOrganizationUnit(OrganizationUnit organizationUnit) {
		this.organizationUnit = organizationUnit;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hostname")
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "ipaddress")
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "uri")
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
