package it.clevercom.echo.rd.model.entity;
// Generated 28-feb-2017 10.00.08 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodingActor generated by hbm2java
 */
@Entity
@Table(name = "coding_actor")
public class CodingActor implements java.io.Serializable {

	private long idcodingactor;
	private String name;
	private Date created;
	private String updated;
	private String userupdate;
	private boolean active;
	private Set<ServiceCodingActor> serviceCodingActors = new HashSet<ServiceCodingActor>(0);
	private Set<PatientCodingActor> patientCodingActors = new HashSet<PatientCodingActor>(0);

	public CodingActor() {
	}

	public CodingActor(long idcodingactor, String name, Date created, String updated, String userupdate,
			boolean active) {
		this.idcodingactor = idcodingactor;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public CodingActor(long idcodingactor, String name, Date created, String updated, String userupdate, boolean active,
			Set<ServiceCodingActor> serviceCodingActors, Set<PatientCodingActor> patientCodingActors) {
		this.idcodingactor = idcodingactor;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.serviceCodingActors = serviceCodingActors;
		this.patientCodingActors = patientCodingActors;
	}

	@Id

	@Column(name = "idcodingactor", unique = true, nullable = false)
	public long getIdcodingactor() {
		return this.idcodingactor;
	}

	public void setIdcodingactor(long idcodingactor) {
		this.idcodingactor = idcodingactor;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated", nullable = false, length = 100)
	public String getUpdated() {
		return this.updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codingActor")
	public Set<ServiceCodingActor> getServiceCodingActors() {
		return this.serviceCodingActors;
	}

	public void setServiceCodingActors(Set<ServiceCodingActor> serviceCodingActors) {
		this.serviceCodingActors = serviceCodingActors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codingActor")
	public Set<PatientCodingActor> getPatientCodingActors() {
		return this.patientCodingActors;
	}

	public void setPatientCodingActors(Set<PatientCodingActor> patientCodingActors) {
		this.patientCodingActors = patientCodingActors;
	}

}
