package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "COUNTRY")
public class Country implements java.io.Serializable {

	private long idcountry;
	private String countryname;
	private String countrynicename;
	private String countryiso2;
	private String countryiso3;
	private Long countryisonumcode;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;
	private Set<Region> regions = new HashSet<Region>(0);

	public Country() {
	}

	public Country(long idcountry, Serializable created, Serializable updated, String userupdate, short active) {
		this.idcountry = idcountry;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Country(long idcountry, String countryname, String countrynicename, String countryiso2, String countryiso3,
			Long countryisonumcode, Serializable created, Serializable updated, String userupdate, short active,
			Set<Region> regions) {
		this.idcountry = idcountry;
		this.countryname = countryname;
		this.countrynicename = countrynicename;
		this.countryiso2 = countryiso2;
		this.countryiso3 = countryiso3;
		this.countryisonumcode = countryisonumcode;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.regions = regions;
	}

	@Id

	@Column(name = "IDCOUNTRY", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdcountry() {
		return this.idcountry;
	}

	public void setIdcountry(long idcountry) {
		this.idcountry = idcountry;
	}

	@Column(name = "COUNTRYNAME", length = 100)
	public String getCountryname() {
		return this.countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}

	@Column(name = "COUNTRYNICENAME", length = 100)
	public String getCountrynicename() {
		return this.countrynicename;
	}

	public void setCountrynicename(String countrynicename) {
		this.countrynicename = countrynicename;
	}

	@Column(name = "COUNTRYISO2", length = 10)
	public String getCountryiso2() {
		return this.countryiso2;
	}

	public void setCountryiso2(String countryiso2) {
		this.countryiso2 = countryiso2;
	}

	@Column(name = "COUNTRYISO3", length = 10)
	public String getCountryiso3() {
		return this.countryiso3;
	}

	public void setCountryiso3(String countryiso3) {
		this.countryiso3 = countryiso3;
	}

	@Column(name = "COUNTRYISONUMCODE", precision = 10, scale = 0)
	public Long getCountryisonumcode() {
		return this.countryisonumcode;
	}

	public void setCountryisonumcode(Long countryisonumcode) {
		this.countryisonumcode = countryisonumcode;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}
