package it.clevercom.echo.rd.model.entity;
// Generated 21-feb-2017 16.05.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hl7InboundMessage generated by hbm2java
 */
@Entity
@Table(name = "hl7_inbound_message")
public class Hl7InboundMessage implements java.io.Serializable {

	private long idinboundmessage;
	private String messagecontrolid;
	private String message;
	private String status;
	private String messagetype;
	private Date received;

	public Hl7InboundMessage() {
	}

	public Hl7InboundMessage(long idinboundmessage, String messagecontrolid, String message, String status,
			String messagetype, Date received) {
		this.idinboundmessage = idinboundmessage;
		this.messagecontrolid = messagecontrolid;
		this.message = message;
		this.status = status;
		this.messagetype = messagetype;
		this.received = received;
	}

	@Id

	@Column(name = "idinboundmessage", unique = true, nullable = false)
	public long getIdinboundmessage() {
		return this.idinboundmessage;
	}

	public void setIdinboundmessage(long idinboundmessage) {
		this.idinboundmessage = idinboundmessage;
	}

	@Column(name = "messagecontrolid", nullable = false)
	public String getMessagecontrolid() {
		return this.messagecontrolid;
	}

	public void setMessagecontrolid(String messagecontrolid) {
		this.messagecontrolid = messagecontrolid;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "messagetype", nullable = false, length = 10)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received", nullable = false, length = 29)
	public Date getReceived() {
		return this.received;
	}

	public void setReceived(Date received) {
		this.received = received;
	}

}
