package it.clevercom.echo.rd.model.entity;
// Generated 7-mar-2017 22.12.30 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Hl7Order generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="rd_hl7_order"
)
public class Hl7Order  implements java.io.Serializable {


     private Long idhl7order;

    public Hl7Order() {
    }

   
     @SequenceGenerator(name="it.clevercom.echo.rd.model.entity.Hl7OrderIdGenerator")@Id @GeneratedValue(strategy=SEQUENCE, generator="it.clevercom.echo.rd.model.entity.Hl7OrderIdGenerator")

    
    @Column(name="idhl7order", unique=true, nullable=false)
    public Long getIdhl7order() {
        return this.idhl7order;
    }
    
    public void setIdhl7order(Long idhl7order) {
        this.idhl7order = idhl7order;
    }




}


