package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hl7outboundmessage generated by hbm2java
 */
@Entity
@Table(name = "HL7OUTBOUNDMESSAGE")
public class Hl7outboundmessage implements java.io.Serializable {

	private long id;
	private String messagecontrolid;
	private Clob message;
	private String status;
	private String messagetype;
	private Serializable sent;

	public Hl7outboundmessage() {
	}

	public Hl7outboundmessage(long id, String messagecontrolid, Clob message, String status, String messagetype,
			Serializable sent) {
		this.id = id;
		this.messagecontrolid = messagecontrolid;
		this.message = message;
		this.status = status;
		this.messagetype = messagetype;
		this.sent = sent;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "MESSAGECONTROLID", nullable = false)
	public String getMessagecontrolid() {
		return this.messagecontrolid;
	}

	public void setMessagecontrolid(String messagecontrolid) {
		this.messagecontrolid = messagecontrolid;
	}

	@Column(name = "MESSAGE", nullable = false)
	public Clob getMessage() {
		return this.message;
	}

	public void setMessage(Clob message) {
		this.message = message;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "MESSAGETYPE", nullable = false, length = 10)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "SENT", nullable = false)
	public Serializable getSent() {
		return this.sent;
	}

	public void setSent(Serializable sent) {
		this.sent = sent;
	}

}
