package it.clevercom.echo.rd.model.entity;
// Generated 21-feb-2017 16.05.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Icd9PatologyGroup generated by hbm2java
 */
@Entity
@Table(name = "icd9_patology_group")
public class Icd9PatologyGroup implements java.io.Serializable {

	private String codeicd9group;
	private String description;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;
	private Set<Icd9Patology> icd9Patologies = new HashSet<Icd9Patology>(0);

	public Icd9PatologyGroup() {
	}

	public Icd9PatologyGroup(String codeicd9group, String description, Date created, Date updated, String userupdate,
			boolean active) {
		this.codeicd9group = codeicd9group;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Icd9PatologyGroup(String codeicd9group, String description, Date created, Date updated, String userupdate,
			boolean active, Set<Icd9Patology> icd9Patologies) {
		this.codeicd9group = codeicd9group;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.icd9Patologies = icd9Patologies;
	}

	@Id

	@Column(name = "codeicd9group", unique = true, nullable = false, length = 5)
	public String getCodeicd9group() {
		return this.codeicd9group;
	}

	public void setCodeicd9group(String codeicd9group) {
		this.codeicd9group = codeicd9group;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "icd9PatologyGroup")
	public Set<Icd9Patology> getIcd9Patologies() {
		return this.icd9Patologies;
	}

	public void setIcd9Patologies(Set<Icd9Patology> icd9Patologies) {
		this.icd9Patologies = icd9Patologies;
	}

}
