package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modality generated by hbm2java
 */
@Entity
@Table(name = "MODALITY")
public class Modality implements java.io.Serializable {

	private long idmodality;
	private Organizationunit organizationunit;
	private String name;
	private String description;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;
	private Set<Service> services = new HashSet<Service>(0);
	private Set<Worklist> worklists = new HashSet<Worklist>(0);

	public Modality() {
	}

	public Modality(long idmodality, Organizationunit organizationunit, String name, Serializable created,
			Serializable updated, String userupdate, short active) {
		this.idmodality = idmodality;
		this.organizationunit = organizationunit;
		this.name = name;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Modality(long idmodality, Organizationunit organizationunit, String name, String description,
			Serializable created, Serializable updated, String userupdate, short active, Set<Service> services,
			Set<Worklist> worklists) {
		this.idmodality = idmodality;
		this.organizationunit = organizationunit;
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.services = services;
		this.worklists = worklists;
	}

	@Id

	@Column(name = "IDMODALITY", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdmodality() {
		return this.idmodality;
	}

	public void setIdmodality(long idmodality) {
		this.idmodality = idmodality;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDORGANIZATIONUNIT", nullable = false)
	public Organizationunit getOrganizationunit() {
		return this.organizationunit;
	}

	public void setOrganizationunit(Organizationunit organizationunit) {
		this.organizationunit = organizationunit;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "MODALITY_SERVICE", joinColumns = {
			@JoinColumn(name = "IDMODALITY", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDSERVICE", nullable = false, updatable = false) })
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modality")
	public Set<Worklist> getWorklists() {
		return this.worklists;
	}

	public void setWorklists(Set<Worklist> worklists) {
		this.worklists = worklists;
	}

}
