package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipality generated by hbm2java
 */
@Entity
@Table(name = "MUNICIPALITY")
public class Municipality implements java.io.Serializable {

	private long idmunicipality;
	private Province province;
	private String municipalityname;
	private String municipalitystdcode;
	private Serializable created;
	private Serializable updated;
	private String updateuser;
	private short active;
	private Set<Patient> patients = new HashSet<Patient>(0);
	private Set<Risuser> risusers = new HashSet<Risuser>(0);

	public Municipality() {
	}

	public Municipality(long idmunicipality, Province province, Serializable created, Serializable updated,
			String updateuser, short active) {
		this.idmunicipality = idmunicipality;
		this.province = province;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
	}

	public Municipality(long idmunicipality, Province province, String municipalityname, String municipalitystdcode,
			Serializable created, Serializable updated, String updateuser, short active, Set<Patient> patients,
			Set<Risuser> risusers) {
		this.idmunicipality = idmunicipality;
		this.province = province;
		this.municipalityname = municipalityname;
		this.municipalitystdcode = municipalitystdcode;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
		this.patients = patients;
		this.risusers = risusers;
	}

	@Id

	@Column(name = "IDMUNICIPALITY", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdmunicipality() {
		return this.idmunicipality;
	}

	public void setIdmunicipality(long idmunicipality) {
		this.idmunicipality = idmunicipality;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPROVINCE", nullable = false)
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	@Column(name = "MUNICIPALITYNAME", length = 100)
	public String getMunicipalityname() {
		return this.municipalityname;
	}

	public void setMunicipalityname(String municipalityname) {
		this.municipalityname = municipalityname;
	}

	@Column(name = "MUNICIPALITYSTDCODE", length = 10)
	public String getMunicipalitystdcode() {
		return this.municipalitystdcode;
	}

	public void setMunicipalitystdcode(String municipalitystdcode) {
		this.municipalitystdcode = municipalitystdcode;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "UPDATEUSER", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipality")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipality")
	public Set<Risuser> getRisusers() {
		return this.risusers;
	}

	public void setRisusers(Set<Risuser> risusers) {
		this.risusers = risusers;
	}

}
