package it.clevercom.echo.rd.model.entity;
// Generated 17-feb-2017 17.22.02 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Municipality generated by hbm2java
 */
@Entity
@Table(name = "municipality")
public class Municipality implements java.io.Serializable {

	private long idmunicipality;
	private Province province;
	private String municipalityname;
	private String municipalitystdcode;
	private Date created;
	private Date updated;
	private String updateuser;
	private boolean active;
	private Set<Patient> patients = new HashSet<Patient>(0);
	private Set<User> users = new HashSet<User>(0);

	public Municipality() {
	}

	public Municipality(long idmunicipality, Province province, Date created, Date updated, String updateuser,
			boolean active) {
		this.idmunicipality = idmunicipality;
		this.province = province;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
	}

	public Municipality(long idmunicipality, Province province, String municipalityname, String municipalitystdcode,
			Date created, Date updated, String updateuser, boolean active, Set<Patient> patients, Set<User> users) {
		this.idmunicipality = idmunicipality;
		this.province = province;
		this.municipalityname = municipalityname;
		this.municipalitystdcode = municipalitystdcode;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
		this.patients = patients;
		this.users = users;
	}

	@Id

	@Column(name = "idmunicipality", unique = true, nullable = false)
	public long getIdmunicipality() {
		return this.idmunicipality;
	}

	public void setIdmunicipality(long idmunicipality) {
		this.idmunicipality = idmunicipality;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprovince", nullable = false)
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	@Column(name = "municipalityname", length = 100)
	public String getMunicipalityname() {
		return this.municipalityname;
	}

	public void setMunicipalityname(String municipalityname) {
		this.municipalityname = municipalityname;
	}

	@Column(name = "municipalitystdcode", length = 10)
	public String getMunicipalitystdcode() {
		return this.municipalitystdcode;
	}

	public void setMunicipalitystdcode(String municipalitystdcode) {
		this.municipalitystdcode = municipalitystdcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "updateuser", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipality")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipality")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
