package it.clevercom.echo.rd.model.entity;
// Generated 7-mar-2017 15.16.14 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientCodingActorId generated by hbm2java
 */
@Embeddable
public class PatientCodingActorId  implements java.io.Serializable {


     private Long idpatient;
     private Long idcodingactor;

    public PatientCodingActorId() {
    }

    public PatientCodingActorId(Long idpatient, Long idcodingactor) {
       this.idpatient = idpatient;
       this.idcodingactor = idcodingactor;
    }
   


    @Column(name="idpatient", nullable=false)
    public Long getIdpatient() {
        return this.idpatient;
    }
    
    public void setIdpatient(Long idpatient) {
        this.idpatient = idpatient;
    }


    @Column(name="idcodingactor", nullable=false)
    public Long getIdcodingactor() {
        return this.idcodingactor;
    }
    
    public void setIdcodingactor(Long idcodingactor) {
        this.idcodingactor = idcodingactor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientCodingActorId) ) return false;
		 PatientCodingActorId castOther = ( PatientCodingActorId ) other; 
         
		 return ( (this.getIdpatient()==castOther.getIdpatient()) || ( this.getIdpatient()!=null && castOther.getIdpatient()!=null && this.getIdpatient().equals(castOther.getIdpatient()) ) )
 && ( (this.getIdcodingactor()==castOther.getIdcodingactor()) || ( this.getIdcodingactor()!=null && castOther.getIdcodingactor()!=null && this.getIdcodingactor().equals(castOther.getIdcodingactor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpatient() == null ? 0 : this.getIdpatient().hashCode() );
         result = 37 * result + ( getIdcodingactor() == null ? 0 : this.getIdcodingactor().hashCode() );
         return result;
   }   


}


