package it.clevercom.echo.rd.model.entity;
// Generated 28-feb-2017 10.00.08 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientCodingActor generated by hbm2java
 */
@Entity
@Table(name = "patient_coding_actor")
public class PatientCodingActor implements java.io.Serializable {

	private PatientCodingActorId id;
	private CodingActor codingActor;
	private Patient patient;

	public PatientCodingActor() {
	}

	public PatientCodingActor(PatientCodingActorId id) {
		this.id = id;
	}

	public PatientCodingActor(PatientCodingActorId id, CodingActor codingActor, Patient patient) {
		this.id = id;
		this.codingActor = codingActor;
		this.patient = patient;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idpatient", column = @Column(name = "idpatient")),
			@AttributeOverride(name = "idcodingactor", column = @Column(name = "idcodingactor")),
			@AttributeOverride(name = "externalcode", column = @Column(name = "externalcode", length = 100)),
			@AttributeOverride(name = "created", column = @Column(name = "created", nullable = false, length = 29)),
			@AttributeOverride(name = "updated", column = @Column(name = "updated", nullable = false, length = 29)),
			@AttributeOverride(name = "userupdate", column = @Column(name = "userupdate", nullable = false, length = 100)),
			@AttributeOverride(name = "active", column = @Column(name = "active", nullable = false)) })
	public PatientCodingActorId getId() {
		return this.id;
	}

	public void setId(PatientCodingActorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcodingactor", insertable = false, updatable = false)
	public CodingActor getCodingActor() {
		return this.codingActor;
	}

	public void setCodingActor(CodingActor codingActor) {
		this.codingActor = codingActor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpatient", insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

}
