package it.clevercom.echo.rd.model.entity;
// Generated 7-mar-2017 15.16.14 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhraseBook generated by hbm2java
 */
@Entity
@Table(name="rd_phrase_book"
)
public class PhraseBook  implements java.io.Serializable {


     private Long idphrasebook;
     private User user;
     private String title;
     private String body;
     private Date created;
     private Date updated;
     private String userupdate;
     private boolean active;

    public PhraseBook() {
    }

	
    public PhraseBook(Long idphrasebook, Date created, Date updated, String userupdate, boolean active) {
        this.idphrasebook = idphrasebook;
        this.created = created;
        this.updated = updated;
        this.userupdate = userupdate;
        this.active = active;
    }
    public PhraseBook(Long idphrasebook, User user, String title, String body, Date created, Date updated, String userupdate, boolean active) {
       this.idphrasebook = idphrasebook;
       this.user = user;
       this.title = title;
       this.body = body;
       this.created = created;
       this.updated = updated;
       this.userupdate = userupdate;
       this.active = active;
    }
   
     @Id 

    
    @Column(name="idphrasebook", unique=true, nullable=false)
    public Long getIdphrasebook() {
        return this.idphrasebook;
    }
    
    public void setIdphrasebook(Long idphrasebook) {
        this.idphrasebook = idphrasebook;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iduser")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="body")
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="userupdate", nullable=false, length=100)
    public String getUserupdate() {
        return this.userupdate;
    }
    
    public void setUserupdate(String userupdate) {
        this.userupdate = userupdate;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


