package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phrasebook generated by hbm2java
 */
@Entity
@Table(name = "PHRASEBOOK")
public class Phrasebook implements java.io.Serializable {

	private long idphrasebook;
	private Risuser risuser;
	private String title;
	private String body;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;

	public Phrasebook() {
	}

	public Phrasebook(long idphrasebook, Serializable created, Serializable updated, String userupdate, short active) {
		this.idphrasebook = idphrasebook;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Phrasebook(long idphrasebook, Risuser risuser, String title, String body, Serializable created,
			Serializable updated, String userupdate, short active) {
		this.idphrasebook = idphrasebook;
		this.risuser = risuser;
		this.title = title;
		this.body = body;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "IDPHRASEBOOK", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdphrasebook() {
		return this.idphrasebook;
	}

	public void setIdphrasebook(long idphrasebook) {
		this.idphrasebook = idphrasebook;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDRISUSER")
	public Risuser getRisuser() {
		return this.risuser;
	}

	public void setRisuser(Risuser risuser) {
		this.risuser = risuser;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "BODY", length = 4000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

}
