package it.clevercom.echo.rd.model.entity;
// Generated 7-mar-2017 22.12.30 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Province generated by hbm2java
 */
@Entity
@DynamicUpdate
@DynamicInsert
@Table(name="rd_province"
)
public class Province  implements java.io.Serializable {


     private Long idprovince;
     private Region region;
     private String provincename;
     private String provincestdcode;
     private Date created;
     private Date updated;
     private String userupdate;
     private boolean active;
     private Set<Municipality> municipalities = new HashSet<Municipality>(0);

    public Province() {
    }

	
    public Province(Date created, Date updated, String userupdate, boolean active) {
        this.created = created;
        this.updated = updated;
        this.userupdate = userupdate;
        this.active = active;
    }
    public Province(Region region, String provincename, String provincestdcode, Date created, Date updated, String userupdate, boolean active, Set<Municipality> municipalities) {
       this.region = region;
       this.provincename = provincename;
       this.provincestdcode = provincestdcode;
       this.created = created;
       this.updated = updated;
       this.userupdate = userupdate;
       this.active = active;
       this.municipalities = municipalities;
    }
   
     @SequenceGenerator(name="it.clevercom.echo.rd.model.entity.ProvinceIdGenerator")@Id @GeneratedValue(strategy=SEQUENCE, generator="it.clevercom.echo.rd.model.entity.ProvinceIdGenerator")

    
    @Column(name="idprovince", unique=true, nullable=false)
    public Long getIdprovince() {
        return this.idprovince;
    }
    
    public void setIdprovince(Long idprovince) {
        this.idprovince = idprovince;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregion")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

    
    @Column(name="provincename", length=100)
    public String getProvincename() {
        return this.provincename;
    }
    
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    
    @Column(name="provincestdcode", length=10)
    public String getProvincestdcode() {
        return this.provincestdcode;
    }
    
    public void setProvincestdcode(String provincestdcode) {
        this.provincestdcode = provincestdcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="userupdate", nullable=false, length=100)
    public String getUserupdate() {
        return this.userupdate;
    }
    
    public void setUserupdate(String userupdate) {
        this.userupdate = userupdate;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="province")
    public Set<Municipality> getMunicipalities() {
        return this.municipalities;
    }
    
    public void setMunicipalities(Set<Municipality> municipalities) {
        this.municipalities = municipalities;
    }




}


