package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "PROVINCE")
public class Province implements java.io.Serializable {

	private long idprovince;
	private Region region;
	private String provincename;
	private String provincestdcode;
	private Serializable created;
	private Serializable updated;
	private String updateuser;
	private short active;
	private Set<Municipality> municipalities = new HashSet<Municipality>(0);

	public Province() {
	}

	public Province(long idprovince, Region region, Serializable created, Serializable updated, String updateuser,
			short active) {
		this.idprovince = idprovince;
		this.region = region;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
	}

	public Province(long idprovince, Region region, String provincename, String provincestdcode, Serializable created,
			Serializable updated, String updateuser, short active, Set<Municipality> municipalities) {
		this.idprovince = idprovince;
		this.region = region;
		this.provincename = provincename;
		this.provincestdcode = provincestdcode;
		this.created = created;
		this.updated = updated;
		this.updateuser = updateuser;
		this.active = active;
		this.municipalities = municipalities;
	}

	@Id

	@Column(name = "IDPROVINCE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdprovince() {
		return this.idprovince;
	}

	public void setIdprovince(long idprovince) {
		this.idprovince = idprovince;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGION", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "PROVINCENAME", length = 100)
	public String getProvincename() {
		return this.provincename;
	}

	public void setProvincename(String provincename) {
		this.provincename = provincename;
	}

	@Column(name = "PROVINCESTDCODE", length = 10)
	public String getProvincestdcode() {
		return this.provincestdcode;
	}

	public void setProvincestdcode(String provincestdcode) {
		this.provincestdcode = provincestdcode;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "UPDATEUSER", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	public Set<Municipality> getMunicipalities() {
		return this.municipalities;
	}

	public void setMunicipalities(Set<Municipality> municipalities) {
		this.municipalities = municipalities;
	}

}
