package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Radiologyordertracking generated by hbm2java
 */
@Entity
@Table(name = "RADIOLOGYORDERTRACKING")
public class Radiologyordertracking implements java.io.Serializable {

	private BigDecimal idordertracking;
	private BigDecimal idorder;
	private BigDecimal idradiologytask;
	private String statuscode;
	private String prioritycode;
	private String acquisitionchannel;
	private Date creationdate;
	private Date scheduleddate;
	private Date acceptancedate;
	private BigDecimal duration;
	private BigDecimal originorganizationunitid;
	private BigDecimal targetorganizationunitid;
	private String requestingphysician;
	private String orderreason;
	private String rejectreason;
	private String clinicalhistory;
	private String notes;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private Short active;

	public Radiologyordertracking() {
	}

	public Radiologyordertracking(BigDecimal idordertracking, BigDecimal idorder, BigDecimal idradiologytask,
			String statuscode, String prioritycode, String acquisitionchannel, Date creationdate, Serializable created,
			Serializable updated, String userupdate) {
		this.idordertracking = idordertracking;
		this.idorder = idorder;
		this.idradiologytask = idradiologytask;
		this.statuscode = statuscode;
		this.prioritycode = prioritycode;
		this.acquisitionchannel = acquisitionchannel;
		this.creationdate = creationdate;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
	}

	public Radiologyordertracking(BigDecimal idordertracking, BigDecimal idorder, BigDecimal idradiologytask,
			String statuscode, String prioritycode, String acquisitionchannel, Date creationdate, Date scheduleddate,
			Date acceptancedate, BigDecimal duration, BigDecimal originorganizationunitid,
			BigDecimal targetorganizationunitid, String requestingphysician, String orderreason, String rejectreason,
			String clinicalhistory, String notes, Serializable created, Serializable updated, String userupdate,
			Short active) {
		this.idordertracking = idordertracking;
		this.idorder = idorder;
		this.idradiologytask = idradiologytask;
		this.statuscode = statuscode;
		this.prioritycode = prioritycode;
		this.acquisitionchannel = acquisitionchannel;
		this.creationdate = creationdate;
		this.scheduleddate = scheduleddate;
		this.acceptancedate = acceptancedate;
		this.duration = duration;
		this.originorganizationunitid = originorganizationunitid;
		this.targetorganizationunitid = targetorganizationunitid;
		this.requestingphysician = requestingphysician;
		this.orderreason = orderreason;
		this.rejectreason = rejectreason;
		this.clinicalhistory = clinicalhistory;
		this.notes = notes;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "IDORDERTRACKING", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdordertracking() {
		return this.idordertracking;
	}

	public void setIdordertracking(BigDecimal idordertracking) {
		this.idordertracking = idordertracking;
	}

	@Column(name = "IDORDER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdorder() {
		return this.idorder;
	}

	public void setIdorder(BigDecimal idorder) {
		this.idorder = idorder;
	}

	@Column(name = "IDRADIOLOGYTASK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdradiologytask() {
		return this.idradiologytask;
	}

	public void setIdradiologytask(BigDecimal idradiologytask) {
		this.idradiologytask = idradiologytask;
	}

	@Column(name = "STATUSCODE", nullable = false, length = 100)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "PRIORITYCODE", nullable = false, length = 100)
	public String getPrioritycode() {
		return this.prioritycode;
	}

	public void setPrioritycode(String prioritycode) {
		this.prioritycode = prioritycode;
	}

	@Column(name = "ACQUISITIONCHANNEL", nullable = false, length = 20)
	public String getAcquisitionchannel() {
		return this.acquisitionchannel;
	}

	public void setAcquisitionchannel(String acquisitionchannel) {
		this.acquisitionchannel = acquisitionchannel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATIONDATE", nullable = false, length = 7)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SCHEDULEDDATE", length = 7)
	public Date getScheduleddate() {
		return this.scheduleddate;
	}

	public void setScheduleddate(Date scheduleddate) {
		this.scheduleddate = scheduleddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACCEPTANCEDATE", length = 7)
	public Date getAcceptancedate() {
		return this.acceptancedate;
	}

	public void setAcceptancedate(Date acceptancedate) {
		this.acceptancedate = acceptancedate;
	}

	@Column(name = "DURATION", precision = 22, scale = 0)
	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	@Column(name = "ORIGINORGANIZATIONUNITID", precision = 22, scale = 0)
	public BigDecimal getOriginorganizationunitid() {
		return this.originorganizationunitid;
	}

	public void setOriginorganizationunitid(BigDecimal originorganizationunitid) {
		this.originorganizationunitid = originorganizationunitid;
	}

	@Column(name = "TARGETORGANIZATIONUNITID", precision = 22, scale = 0)
	public BigDecimal getTargetorganizationunitid() {
		return this.targetorganizationunitid;
	}

	public void setTargetorganizationunitid(BigDecimal targetorganizationunitid) {
		this.targetorganizationunitid = targetorganizationunitid;
	}

	@Column(name = "REQUESTINGPHYSICIAN")
	public String getRequestingphysician() {
		return this.requestingphysician;
	}

	public void setRequestingphysician(String requestingphysician) {
		this.requestingphysician = requestingphysician;
	}

	@Column(name = "ORDERREASON", length = 1000)
	public String getOrderreason() {
		return this.orderreason;
	}

	public void setOrderreason(String orderreason) {
		this.orderreason = orderreason;
	}

	@Column(name = "REJECTREASON", length = 1000)
	public String getRejectreason() {
		return this.rejectreason;
	}

	public void setRejectreason(String rejectreason) {
		this.rejectreason = rejectreason;
	}

	@Column(name = "CLINICALHISTORY", length = 1000)
	public String getClinicalhistory() {
		return this.clinicalhistory;
	}

	public void setClinicalhistory(String clinicalhistory) {
		this.clinicalhistory = clinicalhistory;
	}

	@Column(name = "NOTES", length = 1000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", precision = 3, scale = 0)
	public Short getActive() {
		return this.active;
	}

	public void setActive(Short active) {
		this.active = active;
	}

}
