package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Radiologytask generated by hbm2java
 */
@Entity
@Table(name = "RADIOLOGYTASK")
public class Radiologytask implements java.io.Serializable {

	private long idradiologytask;
	private Status status;
	private Patient patient;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<Radiologyorder> radiologyorders = new HashSet<Radiologyorder>(0);
	private Set<Worklist> worklists = new HashSet<Worklist>(0);

	public Radiologytask() {
	}

	public Radiologytask(long idradiologytask, Status status, Patient patient) {
		this.idradiologytask = idradiologytask;
		this.status = status;
		this.patient = patient;
	}

	public Radiologytask(long idradiologytask, Status status, Patient patient, Set<Report> reports,
			Set<Radiologyorder> radiologyorders, Set<Worklist> worklists) {
		this.idradiologytask = idradiologytask;
		this.status = status;
		this.patient = patient;
		this.reports = reports;
		this.radiologyorders = radiologyorders;
		this.worklists = worklists;
	}

	@Id

	@Column(name = "IDRADIOLOGYTASK", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdradiologytask() {
		return this.idradiologytask;
	}

	public void setIdradiologytask(long idradiologytask) {
		this.idradiologytask = idradiologytask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUSCODE", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPATIENT", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "radiologytask")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "radiologytask")
	public Set<Radiologyorder> getRadiologyorders() {
		return this.radiologyorders;
	}

	public void setRadiologyorders(Set<Radiologyorder> radiologyorders) {
		this.radiologyorders = radiologyorders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "radiologytask")
	public Set<Worklist> getWorklists() {
		return this.worklists;
	}

	public void setWorklists(Set<Worklist> worklists) {
		this.worklists = worklists;
	}

}
