package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "REPORT")
public class Report implements java.io.Serializable {

	private long idreport;
	private Status status;
	private Worklist worklist;
	private Radiologytask radiologytask;
	private Long accessionnumber;
	private Serializable creationdate;
	private Serializable completiondate;
	private String body;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;
	private Set<Reporttracking> reporttrackings = new HashSet<Reporttracking>(0);
	private Set<Risuser> risusers = new HashSet<Risuser>(0);

	public Report() {
	}

	public Report(long idreport, Status status, Worklist worklist, Radiologytask radiologytask,
			Serializable creationdate, String body, Serializable created, Serializable updated, String userupdate,
			short active) {
		this.idreport = idreport;
		this.status = status;
		this.worklist = worklist;
		this.radiologytask = radiologytask;
		this.creationdate = creationdate;
		this.body = body;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Report(long idreport, Status status, Worklist worklist, Radiologytask radiologytask, Long accessionnumber,
			Serializable creationdate, Serializable completiondate, String body, Serializable created,
			Serializable updated, String userupdate, short active, Set<Reporttracking> reporttrackings,
			Set<Risuser> risusers) {
		this.idreport = idreport;
		this.status = status;
		this.worklist = worklist;
		this.radiologytask = radiologytask;
		this.accessionnumber = accessionnumber;
		this.creationdate = creationdate;
		this.completiondate = completiondate;
		this.body = body;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.reporttrackings = reporttrackings;
		this.risusers = risusers;
	}

	@Id

	@Column(name = "IDREPORT", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdreport() {
		return this.idreport;
	}

	public void setIdreport(long idreport) {
		this.idreport = idreport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUSCODE", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDWORKLIST", nullable = false)
	public Worklist getWorklist() {
		return this.worklist;
	}

	public void setWorklist(Worklist worklist) {
		this.worklist = worklist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDRADIOLOGYTASK", nullable = false)
	public Radiologytask getRadiologytask() {
		return this.radiologytask;
	}

	public void setRadiologytask(Radiologytask radiologytask) {
		this.radiologytask = radiologytask;
	}

	@Column(name = "ACCESSIONNUMBER", precision = 10, scale = 0)
	public Long getAccessionnumber() {
		return this.accessionnumber;
	}

	public void setAccessionnumber(Long accessionnumber) {
		this.accessionnumber = accessionnumber;
	}

	@Column(name = "CREATIONDATE", nullable = false)
	public Serializable getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Serializable creationdate) {
		this.creationdate = creationdate;
	}

	@Column(name = "COMPLETIONDATE")
	public Serializable getCompletiondate() {
		return this.completiondate;
	}

	public void setCompletiondate(Serializable completiondate) {
		this.completiondate = completiondate;
	}

	@Column(name = "BODY", nullable = false, length = 4000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "report")
	public Set<Reporttracking> getReporttrackings() {
		return this.reporttrackings;
	}

	public void setReporttrackings(Set<Reporttracking> reporttrackings) {
		this.reporttrackings = reporttrackings;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USER_REPORT", joinColumns = {
			@JoinColumn(name = "IDREPORT", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDUSER", nullable = false, updatable = false) })
	public Set<Risuser> getRisusers() {
		return this.risusers;
	}

	public void setRisusers(Set<Risuser> risusers) {
		this.risusers = risusers;
	}

}
