package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reporttracking generated by hbm2java
 */
@Entity
@Table(name = "REPORTTRACKING")
public class Reporttracking implements java.io.Serializable {

	private long idreporttracking;
	private Report report;
	private long idradiologytask;
	private Long accessionnumber;
	private String statuscode;
	private Serializable creationdate;
	private Serializable completiondate;
	private String body;
	private long idworklist;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;

	public Reporttracking() {
	}

	public Reporttracking(long idreporttracking, Report report, long idradiologytask, String statuscode,
			Serializable creationdate, String body, long idworklist, Serializable created, Serializable updated,
			String userupdate, short active) {
		this.idreporttracking = idreporttracking;
		this.report = report;
		this.idradiologytask = idradiologytask;
		this.statuscode = statuscode;
		this.creationdate = creationdate;
		this.body = body;
		this.idworklist = idworklist;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Reporttracking(long idreporttracking, Report report, long idradiologytask, Long accessionnumber,
			String statuscode, Serializable creationdate, Serializable completiondate, String body, long idworklist,
			Serializable created, Serializable updated, String userupdate, short active) {
		this.idreporttracking = idreporttracking;
		this.report = report;
		this.idradiologytask = idradiologytask;
		this.accessionnumber = accessionnumber;
		this.statuscode = statuscode;
		this.creationdate = creationdate;
		this.completiondate = completiondate;
		this.body = body;
		this.idworklist = idworklist;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "IDREPORTTRACKING", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdreporttracking() {
		return this.idreporttracking;
	}

	public void setIdreporttracking(long idreporttracking) {
		this.idreporttracking = idreporttracking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREPORT", nullable = false)
	public Report getReport() {
		return this.report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

	@Column(name = "IDRADIOLOGYTASK", nullable = false, precision = 10, scale = 0)
	public long getIdradiologytask() {
		return this.idradiologytask;
	}

	public void setIdradiologytask(long idradiologytask) {
		this.idradiologytask = idradiologytask;
	}

	@Column(name = "ACCESSIONNUMBER", precision = 10, scale = 0)
	public Long getAccessionnumber() {
		return this.accessionnumber;
	}

	public void setAccessionnumber(Long accessionnumber) {
		this.accessionnumber = accessionnumber;
	}

	@Column(name = "STATUSCODE", nullable = false, length = 100)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "CREATIONDATE", nullable = false)
	public Serializable getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Serializable creationdate) {
		this.creationdate = creationdate;
	}

	@Column(name = "COMPLETIONDATE")
	public Serializable getCompletiondate() {
		return this.completiondate;
	}

	public void setCompletiondate(Serializable completiondate) {
		this.completiondate = completiondate;
	}

	@Column(name = "BODY", nullable = false, length = 4000)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "IDWORKLIST", nullable = false, precision = 10, scale = 0)
	public long getIdworklist() {
		return this.idworklist;
	}

	public void setIdworklist(long idworklist) {
		this.idworklist = idworklist;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

}
