package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "SERVICE")
public class Service implements java.io.Serializable {

	private long idservice;
	private String name;
	private String description;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;
	private Set<Worklist> worklists = new HashSet<Worklist>(0);
	private Set<Modality> modalities = new HashSet<Modality>(0);
	private Set<Radiologyorder> radiologyorders = new HashSet<Radiologyorder>(0);

	public Service() {
	}

	public Service(long idservice, Serializable created, Serializable updated, String userupdate, short active) {
		this.idservice = idservice;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Service(long idservice, String name, String description, Serializable created, Serializable updated,
			String userupdate, short active, Set<Worklist> worklists, Set<Modality> modalities,
			Set<Radiologyorder> radiologyorders) {
		this.idservice = idservice;
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.worklists = worklists;
		this.modalities = modalities;
		this.radiologyorders = radiologyorders;
	}

	@Id

	@Column(name = "IDSERVICE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdservice() {
		return this.idservice;
	}

	public void setIdservice(long idservice) {
		this.idservice = idservice;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<Worklist> getWorklists() {
		return this.worklists;
	}

	public void setWorklists(Set<Worklist> worklists) {
		this.worklists = worklists;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Modality> getModalities() {
		return this.modalities;
	}

	public void setModalities(Set<Modality> modalities) {
		this.modalities = modalities;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Radiologyorder> getRadiologyorders() {
		return this.radiologyorders;
	}

	public void setRadiologyorders(Set<Radiologyorder> radiologyorders) {
		this.radiologyorders = radiologyorders;
	}

}
