package it.clevercom.echo.rd.model.entity;
// Generated 17-feb-2017 17.22.02 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service")
public class Service implements java.io.Serializable {

	private long idservice;
	private String name;
	private String description;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;
	private Set<WorkTask> workTasks = new HashSet<WorkTask>(0);
	private Set<ModalityService> modalityServices = new HashSet<ModalityService>(0);
	private Set<OrderService> orderServices = new HashSet<OrderService>(0);

	public Service() {
	}

	public Service(long idservice, Date created, Date updated, String userupdate, boolean active) {
		this.idservice = idservice;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Service(long idservice, String name, String description, Date created, Date updated, String userupdate,
			boolean active, Set<WorkTask> workTasks, Set<ModalityService> modalityServices,
			Set<OrderService> orderServices) {
		this.idservice = idservice;
		this.name = name;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.workTasks = workTasks;
		this.modalityServices = modalityServices;
		this.orderServices = orderServices;
	}

	@Id

	@Column(name = "idservice", unique = true, nullable = false)
	public long getIdservice() {
		return this.idservice;
	}

	public void setIdservice(long idservice) {
		this.idservice = idservice;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<WorkTask> getWorkTasks() {
		return this.workTasks;
	}

	public void setWorkTasks(Set<WorkTask> workTasks) {
		this.workTasks = workTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ModalityService> getModalityServices() {
		return this.modalityServices;
	}

	public void setModalityServices(Set<ModalityService> modalityServices) {
		this.modalityServices = modalityServices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<OrderService> getOrderServices() {
		return this.orderServices;
	}

	public void setOrderServices(Set<OrderService> orderServices) {
		this.orderServices = orderServices;
	}

}
