package it.clevercom.echo.rd.model.entity;
// Generated 7-mar-2017 15.16.14 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceCodingActor generated by hbm2java
 */
@Entity
@Table(name="rd_service_coding_actor"
)
public class ServiceCodingActor  implements java.io.Serializable {


     private ServiceCodingActorId id;
     private CodingActor codingActor;
     private Service service;
     private String externalcode;
     private Date created;
     private Date updated;
     private String userupdate;
     private boolean active;

    public ServiceCodingActor() {
    }

    public ServiceCodingActor(ServiceCodingActorId id, CodingActor codingActor, Service service, String externalcode, Date created, Date updated, String userupdate, boolean active) {
       this.id = id;
       this.codingActor = codingActor;
       this.service = service;
       this.externalcode = externalcode;
       this.created = created;
       this.updated = updated;
       this.userupdate = userupdate;
       this.active = active;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idservice", column=@Column(name="idservice", nullable=false) ), 
        @AttributeOverride(name="idcodingactor", column=@Column(name="idcodingactor", nullable=false) ) } )
    public ServiceCodingActorId getId() {
        return this.id;
    }
    
    public void setId(ServiceCodingActorId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcodingactor", nullable=false, insertable=false, updatable=false)
    public CodingActor getCodingActor() {
        return this.codingActor;
    }
    
    public void setCodingActor(CodingActor codingActor) {
        this.codingActor = codingActor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservice", nullable=false, insertable=false, updatable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

    
    @Column(name="externalcode", nullable=false, length=100)
    public String getExternalcode() {
        return this.externalcode;
    }
    
    public void setExternalcode(String externalcode) {
        this.externalcode = externalcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="userupdate", nullable=false, length=100)
    public String getUserupdate() {
        return this.userupdate;
    }
    
    public void setUserupdate(String userupdate) {
        this.userupdate = userupdate;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


