package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "STATUS")
public class Status implements java.io.Serializable {

	private String code;
	private String description;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<Radiologytask> radiologytasks = new HashSet<Radiologytask>(0);
	private Set<Worklist> worklists = new HashSet<Worklist>(0);
	private Set<Radiologyorder> radiologyorders = new HashSet<Radiologyorder>(0);

	public Status() {
	}

	public Status(String code, Serializable created, Serializable updated, String userupdate, short active) {
		this.code = code;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Status(String code, String description, Serializable created, Serializable updated, String userupdate,
			short active, Set<Report> reports, Set<Radiologytask> radiologytasks, Set<Worklist> worklists,
			Set<Radiologyorder> radiologyorders) {
		this.code = code;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.reports = reports;
		this.radiologytasks = radiologytasks;
		this.worklists = worklists;
		this.radiologyorders = radiologyorders;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Radiologytask> getRadiologytasks() {
		return this.radiologytasks;
	}

	public void setRadiologytasks(Set<Radiologytask> radiologytasks) {
		this.radiologytasks = radiologytasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Worklist> getWorklists() {
		return this.worklists;
	}

	public void setWorklists(Set<Worklist> worklists) {
		this.worklists = worklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Radiologyorder> getRadiologyorders() {
		return this.radiologyorders;
	}

	public void setRadiologyorders(Set<Radiologyorder> radiologyorders) {
		this.radiologyorders = radiologyorders;
	}

}
