package it.clevercom.echo.rd.model.entity;
// Generated 21-feb-2017 16.05.29 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private long iduser;
	private Municipality municipality;
	private String username;
	private String type;
	private String name;
	private String surname;
	private String gender;
	private String taxcode;
	private Date birthdate;
	private String nationality;
	private String homeaddress;
	private String phonenumber;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;
	private Set<PhraseBook> phraseBooks = new HashSet<PhraseBook>(0);
	private Set<WorkReportUser> workReportUsers = new HashSet<WorkReportUser>(0);
	private Set<WorkTask> workTasks = new HashSet<WorkTask>(0);

	public User() {
	}

	public User(long iduser, String username, String type, String name, String surname, String gender, boolean active) {
		this.iduser = iduser;
		this.username = username;
		this.type = type;
		this.name = name;
		this.surname = surname;
		this.gender = gender;
		this.active = active;
	}

	public User(long iduser, Municipality municipality, String username, String type, String name, String surname,
			String gender, String taxcode, Date birthdate, String nationality, String homeaddress, String phonenumber,
			Date created, Date updated, String userupdate, boolean active, Set<PhraseBook> phraseBooks,
			Set<WorkReportUser> workReportUsers, Set<WorkTask> workTasks) {
		this.iduser = iduser;
		this.municipality = municipality;
		this.username = username;
		this.type = type;
		this.name = name;
		this.surname = surname;
		this.gender = gender;
		this.taxcode = taxcode;
		this.birthdate = birthdate;
		this.nationality = nationality;
		this.homeaddress = homeaddress;
		this.phonenumber = phonenumber;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.phraseBooks = phraseBooks;
		this.workReportUsers = workReportUsers;
		this.workTasks = workTasks;
	}

	@Id

	@Column(name = "iduser", unique = true, nullable = false)
	public long getIduser() {
		return this.iduser;
	}

	public void setIduser(long iduser) {
		this.iduser = iduser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmunicipality")
	public Municipality getMunicipality() {
		return this.municipality;
	}

	public void setMunicipality(Municipality municipality) {
		this.municipality = municipality;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 100)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "taxcode", length = 20)
	public String getTaxcode() {
		return this.taxcode;
	}

	public void setTaxcode(String taxcode) {
		this.taxcode = taxcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 13)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "nationality", length = 100)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "homeaddress", length = 100)
	public String getHomeaddress() {
		return this.homeaddress;
	}

	public void setHomeaddress(String homeaddress) {
		this.homeaddress = homeaddress;
	}

	@Column(name = "phonenumber", length = 100)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 13)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated", length = 13)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<PhraseBook> getPhraseBooks() {
		return this.phraseBooks;
	}

	public void setPhraseBooks(Set<PhraseBook> phraseBooks) {
		this.phraseBooks = phraseBooks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<WorkReportUser> getWorkReportUsers() {
		return this.workReportUsers;
	}

	public void setWorkReportUsers(Set<WorkReportUser> workReportUsers) {
		this.workReportUsers = workReportUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<WorkTask> getWorkTasks() {
		return this.workTasks;
	}

	public void setWorkTasks(Set<WorkTask> workTasks) {
		this.workTasks = workTasks;
	}

}
