package it.clevercom.echo.rd.model.entity;
// Generated 28-feb-2017 10.00.08 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkStatus generated by hbm2java
 */
@Entity
@Table(name = "work_status")
public class WorkStatus implements java.io.Serializable {

	private String code;
	private String description;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;
	private Set<WorkReport> workReports = new HashSet<WorkReport>(0);
	private Set<WorkTask> workTasks = new HashSet<WorkTask>(0);
	private Set<WorkSession> workSessions = new HashSet<WorkSession>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public WorkStatus() {
	}

	public WorkStatus(String code, Date created, Date updated, String userupdate, boolean active) {
		this.code = code;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public WorkStatus(String code, String description, Date created, Date updated, String userupdate, boolean active,
			Set<WorkReport> workReports, Set<WorkTask> workTasks, Set<WorkSession> workSessions, Set<Order> orders) {
		this.code = code;
		this.description = description;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
		this.workReports = workReports;
		this.workTasks = workTasks;
		this.workSessions = workSessions;
		this.orders = orders;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workStatus")
	public Set<WorkReport> getWorkReports() {
		return this.workReports;
	}

	public void setWorkReports(Set<WorkReport> workReports) {
		this.workReports = workReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workStatus")
	public Set<WorkTask> getWorkTasks() {
		return this.workTasks;
	}

	public void setWorkTasks(Set<WorkTask> workTasks) {
		this.workTasks = workTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workStatus")
	public Set<WorkSession> getWorkSessions() {
		return this.workSessions;
	}

	public void setWorkSessions(Set<WorkSession> workSessions) {
		this.workSessions = workSessions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workStatus")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
