package it.clevercom.echo.rd.model.entity;
// Generated 15-feb-2017 17.20.09 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Worklisttracking generated by hbm2java
 */
@Entity
@Table(name = "WORKLISTTRACKING")
public class Worklisttracking implements java.io.Serializable {

	private long idworklisttracking;
	private Worklist worklist;
	private long idradiologytask;
	private long accessionnumber;
	private String statuscode;
	private String prioritycode;
	private long idservice;
	private long idmodality;
	private Serializable scheduleddate;
	private Serializable executiondate;
	private String studyuuid;
	private Long studyid;
	private long idrisuser;
	private Serializable created;
	private Serializable updated;
	private String userupdate;
	private short active;

	public Worklisttracking() {
	}

	public Worklisttracking(long idworklisttracking, Worklist worklist, long idradiologytask, long accessionnumber,
			String statuscode, String prioritycode, long idservice, long idmodality, Serializable scheduleddate,
			String studyuuid, long idrisuser, Serializable created, Serializable updated, String userupdate,
			short active) {
		this.idworklisttracking = idworklisttracking;
		this.worklist = worklist;
		this.idradiologytask = idradiologytask;
		this.accessionnumber = accessionnumber;
		this.statuscode = statuscode;
		this.prioritycode = prioritycode;
		this.idservice = idservice;
		this.idmodality = idmodality;
		this.scheduleddate = scheduleddate;
		this.studyuuid = studyuuid;
		this.idrisuser = idrisuser;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public Worklisttracking(long idworklisttracking, Worklist worklist, long idradiologytask, long accessionnumber,
			String statuscode, String prioritycode, long idservice, long idmodality, Serializable scheduleddate,
			Serializable executiondate, String studyuuid, Long studyid, long idrisuser, Serializable created,
			Serializable updated, String userupdate, short active) {
		this.idworklisttracking = idworklisttracking;
		this.worklist = worklist;
		this.idradiologytask = idradiologytask;
		this.accessionnumber = accessionnumber;
		this.statuscode = statuscode;
		this.prioritycode = prioritycode;
		this.idservice = idservice;
		this.idmodality = idmodality;
		this.scheduleddate = scheduleddate;
		this.executiondate = executiondate;
		this.studyuuid = studyuuid;
		this.studyid = studyid;
		this.idrisuser = idrisuser;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "IDWORKLISTTRACKING", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdworklisttracking() {
		return this.idworklisttracking;
	}

	public void setIdworklisttracking(long idworklisttracking) {
		this.idworklisttracking = idworklisttracking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDWORKLIST", nullable = false)
	public Worklist getWorklist() {
		return this.worklist;
	}

	public void setWorklist(Worklist worklist) {
		this.worklist = worklist;
	}

	@Column(name = "IDRADIOLOGYTASK", nullable = false, precision = 10, scale = 0)
	public long getIdradiologytask() {
		return this.idradiologytask;
	}

	public void setIdradiologytask(long idradiologytask) {
		this.idradiologytask = idradiologytask;
	}

	@Column(name = "ACCESSIONNUMBER", nullable = false, precision = 10, scale = 0)
	public long getAccessionnumber() {
		return this.accessionnumber;
	}

	public void setAccessionnumber(long accessionnumber) {
		this.accessionnumber = accessionnumber;
	}

	@Column(name = "STATUSCODE", nullable = false, length = 100)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "PRIORITYCODE", nullable = false, length = 100)
	public String getPrioritycode() {
		return this.prioritycode;
	}

	public void setPrioritycode(String prioritycode) {
		this.prioritycode = prioritycode;
	}

	@Column(name = "IDSERVICE", nullable = false, precision = 10, scale = 0)
	public long getIdservice() {
		return this.idservice;
	}

	public void setIdservice(long idservice) {
		this.idservice = idservice;
	}

	@Column(name = "IDMODALITY", nullable = false, precision = 10, scale = 0)
	public long getIdmodality() {
		return this.idmodality;
	}

	public void setIdmodality(long idmodality) {
		this.idmodality = idmodality;
	}

	@Column(name = "SCHEDULEDDATE", nullable = false)
	public Serializable getScheduleddate() {
		return this.scheduleddate;
	}

	public void setScheduleddate(Serializable scheduleddate) {
		this.scheduleddate = scheduleddate;
	}

	@Column(name = "EXECUTIONDATE")
	public Serializable getExecutiondate() {
		return this.executiondate;
	}

	public void setExecutiondate(Serializable executiondate) {
		this.executiondate = executiondate;
	}

	@Column(name = "STUDYUUID", nullable = false, length = 100)
	public String getStudyuuid() {
		return this.studyuuid;
	}

	public void setStudyuuid(String studyuuid) {
		this.studyuuid = studyuuid;
	}

	@Column(name = "STUDYID", precision = 10, scale = 0)
	public Long getStudyid() {
		return this.studyid;
	}

	public void setStudyid(Long studyid) {
		this.studyid = studyid;
	}

	@Column(name = "IDRISUSER", nullable = false, precision = 10, scale = 0)
	public long getIdrisuser() {
		return this.idrisuser;
	}

	public void setIdrisuser(long idrisuser) {
		this.idrisuser = idrisuser;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "USERUPDATE", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 3, scale = 0)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

}
