package it.clevercom.echo.rd.model.entity;
// Generated 17-feb-2017 17.22.02 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkReportLog generated by hbm2java
 */
@Entity
@Table(name = "work_report_log")
public class WorkReportLog implements java.io.Serializable {

	private long idworkreportlog;
	private WorkReport workReport;
	private long idworksession;
	private Long accessionnumber;
	private String statuscode;
	private Date creationdate;
	private Date completiondate;
	private String body;
	private long idworktask;
	private Date created;
	private Date updated;
	private String userupdate;
	private boolean active;

	public WorkReportLog() {
	}

	public WorkReportLog(long idworkreportlog, WorkReport workReport, long idworksession, String statuscode,
			Date creationdate, String body, long idworktask, Date created, Date updated, String userupdate,
			boolean active) {
		this.idworkreportlog = idworkreportlog;
		this.workReport = workReport;
		this.idworksession = idworksession;
		this.statuscode = statuscode;
		this.creationdate = creationdate;
		this.body = body;
		this.idworktask = idworktask;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	public WorkReportLog(long idworkreportlog, WorkReport workReport, long idworksession, Long accessionnumber,
			String statuscode, Date creationdate, Date completiondate, String body, long idworktask, Date created,
			Date updated, String userupdate, boolean active) {
		this.idworkreportlog = idworkreportlog;
		this.workReport = workReport;
		this.idworksession = idworksession;
		this.accessionnumber = accessionnumber;
		this.statuscode = statuscode;
		this.creationdate = creationdate;
		this.completiondate = completiondate;
		this.body = body;
		this.idworktask = idworktask;
		this.created = created;
		this.updated = updated;
		this.userupdate = userupdate;
		this.active = active;
	}

	@Id

	@Column(name = "idworkreportlog", unique = true, nullable = false)
	public long getIdworkreportlog() {
		return this.idworkreportlog;
	}

	public void setIdworkreportlog(long idworkreportlog) {
		this.idworkreportlog = idworkreportlog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idworkreport", nullable = false)
	public WorkReport getWorkReport() {
		return this.workReport;
	}

	public void setWorkReport(WorkReport workReport) {
		this.workReport = workReport;
	}

	@Column(name = "idworksession", nullable = false)
	public long getIdworksession() {
		return this.idworksession;
	}

	public void setIdworksession(long idworksession) {
		this.idworksession = idworksession;
	}

	@Column(name = "accessionnumber")
	public Long getAccessionnumber() {
		return this.accessionnumber;
	}

	public void setAccessionnumber(Long accessionnumber) {
		this.accessionnumber = accessionnumber;
	}

	@Column(name = "statuscode", nullable = false, length = 100)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationdate", nullable = false, length = 29)
	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "completiondate", length = 29)
	public Date getCompletiondate() {
		return this.completiondate;
	}

	public void setCompletiondate(Date completiondate) {
		this.completiondate = completiondate;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "idworktask", nullable = false)
	public long getIdworktask() {
		return this.idworktask;
	}

	public void setIdworktask(long idworktask) {
		this.idworktask = idworktask;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "userupdate", nullable = false, length = 100)
	public String getUserupdate() {
		return this.userupdate;
	}

	public void setUserupdate(String userupdate) {
		this.userupdate = userupdate;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
