package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 11-apr-2017 13.43.21 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CareGiver generated by hbm2java
 */
@Entity
@Table(name="tm_care_giver"
    , uniqueConstraints = @UniqueConstraint(columnNames="taxcode") 
)
public class CareGiver  implements java.io.Serializable {


     private Long idcaregiver;
     private Municipality municipality;
     private String name;
     private String surname;
     private Character gender;
     private String taxcode;
     private Date birthdate;
     private String nationality;
     private String homeaddress;
     private String phonenumber;
     private String username;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<PatientCaregiver> patientCaregivers = new HashSet<PatientCaregiver>(0);

    public CareGiver() {
    }

	
    public CareGiver(Long idcaregiver, String username, Date created, Date updated, boolean active, String updateuser) {
        this.idcaregiver = idcaregiver;
        this.username = username;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public CareGiver(Long idcaregiver, Municipality municipality, String name, String surname, Character gender, String taxcode, Date birthdate, String nationality, String homeaddress, String phonenumber, String username, Date created, Date updated, boolean active, String updateuser, Set<PatientCaregiver> patientCaregivers) {
       this.idcaregiver = idcaregiver;
       this.municipality = municipality;
       this.name = name;
       this.surname = surname;
       this.gender = gender;
       this.taxcode = taxcode;
       this.birthdate = birthdate;
       this.nationality = nationality;
       this.homeaddress = homeaddress;
       this.phonenumber = phonenumber;
       this.username = username;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.patientCaregivers = patientCaregivers;
    }
   
     @Id 

    
    @Column(name="idcaregiver", unique=true, nullable=false)
    public Long getIdcaregiver() {
        return this.idcaregiver;
    }
    
    public void setIdcaregiver(Long idcaregiver) {
        this.idcaregiver = idcaregiver;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmunicipality")
    public Municipality getMunicipality() {
        return this.municipality;
    }
    
    public void setMunicipality(Municipality municipality) {
        this.municipality = municipality;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="taxcode", unique=true, length=50)
    public String getTaxcode() {
        return this.taxcode;
    }
    
    public void setTaxcode(String taxcode) {
        this.taxcode = taxcode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", length=13)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="nationality", length=100)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="homeaddress", length=100)
    public String getHomeaddress() {
        return this.homeaddress;
    }
    
    public void setHomeaddress(String homeaddress) {
        this.homeaddress = homeaddress;
    }

    
    @Column(name="phonenumber", length=100)
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="careGiver")
    public Set<PatientCaregiver> getPatientCaregivers() {
        return this.patientCaregivers;
    }
    
    public void setPatientCaregivers(Set<PatientCaregiver> patientCaregivers) {
        this.patientCaregivers = patientCaregivers;
    }




}


