package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 20-apr-2017 6.54.04 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="tm_country"
)
public class Country  implements java.io.Serializable {


     private Long idcountry;
     private String countryname;
     private String countrynicename;
     private String countryiso2;
     private String countryiso3;
     private Long countryisonumcode;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<Region> regions = new HashSet<Region>(0);

    public Country() {
    }

	
    public Country(Long idcountry, Date created, Date updated, boolean active, String updateuser) {
        this.idcountry = idcountry;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public Country(Long idcountry, String countryname, String countrynicename, String countryiso2, String countryiso3, Long countryisonumcode, Date created, Date updated, boolean active, String updateuser, Set<Region> regions) {
       this.idcountry = idcountry;
       this.countryname = countryname;
       this.countrynicename = countrynicename;
       this.countryiso2 = countryiso2;
       this.countryiso3 = countryiso3;
       this.countryisonumcode = countryisonumcode;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.regions = regions;
    }
   
     @Id 

    
    @Column(name="idcountry", unique=true, nullable=false)
    public Long getIdcountry() {
        return this.idcountry;
    }
    
    public void setIdcountry(Long idcountry) {
        this.idcountry = idcountry;
    }

    
    @Column(name="countryname", length=100)
    public String getCountryname() {
        return this.countryname;
    }
    
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    
    @Column(name="countrynicename", length=100)
    public String getCountrynicename() {
        return this.countrynicename;
    }
    
    public void setCountrynicename(String countrynicename) {
        this.countrynicename = countrynicename;
    }

    
    @Column(name="countryiso2", length=10)
    public String getCountryiso2() {
        return this.countryiso2;
    }
    
    public void setCountryiso2(String countryiso2) {
        this.countryiso2 = countryiso2;
    }

    
    @Column(name="countryiso3", length=10)
    public String getCountryiso3() {
        return this.countryiso3;
    }
    
    public void setCountryiso3(String countryiso3) {
        this.countryiso3 = countryiso3;
    }

    
    @Column(name="countryisonumcode")
    public Long getCountryisonumcode() {
        return this.countryisonumcode;
    }
    
    public void setCountryisonumcode(Long countryisonumcode) {
        this.countryisonumcode = countryisonumcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Region> getRegions() {
        return this.regions;
    }
    
    public void setRegions(Set<Region> regions) {
        this.regions = regions;
    }




}


