package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 11-apr-2017 13.43.21 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DetectionTask generated by hbm2java
 */
@Entity
@Table(name="tm_detection_task"
    , uniqueConstraints = @UniqueConstraint(columnNames="taskuuid") 
)
public class DetectionTask  implements java.io.Serializable {


     private Long iddetectiontask;
     private DetectionPlan detectionPlan;
     private DetectionType detectionType;
     private String description;
     private Date execution;
     private Date schedulefrom;
     private Date scheduleto;
     private Boolean completed;
     private String attachmenturl;
     private String mimetype;
     private String filename;
     private String comment;
     private String taskuuid;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<DetectionResult> detectionResults = new HashSet<DetectionResult>(0);

    public DetectionTask() {
    }

	
    public DetectionTask(Long iddetectiontask, DetectionType detectionType, String taskuuid, Date created, Date updated, boolean active, String updateuser) {
        this.iddetectiontask = iddetectiontask;
        this.detectionType = detectionType;
        this.taskuuid = taskuuid;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public DetectionTask(Long iddetectiontask, DetectionPlan detectionPlan, DetectionType detectionType, String description, Date execution, Date schedulefrom, Date scheduleto, Boolean completed, String attachmenturl, String mimetype, String filename, String comment, String taskuuid, Date created, Date updated, boolean active, String updateuser, Set<DetectionResult> detectionResults) {
       this.iddetectiontask = iddetectiontask;
       this.detectionPlan = detectionPlan;
       this.detectionType = detectionType;
       this.description = description;
       this.execution = execution;
       this.schedulefrom = schedulefrom;
       this.scheduleto = scheduleto;
       this.completed = completed;
       this.attachmenturl = attachmenturl;
       this.mimetype = mimetype;
       this.filename = filename;
       this.comment = comment;
       this.taskuuid = taskuuid;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.detectionResults = detectionResults;
    }
   
     @Id 

    
    @Column(name="iddetectiontask", unique=true, nullable=false)
    public Long getIddetectiontask() {
        return this.iddetectiontask;
    }
    
    public void setIddetectiontask(Long iddetectiontask) {
        this.iddetectiontask = iddetectiontask;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddetectionplan")
    public DetectionPlan getDetectionPlan() {
        return this.detectionPlan;
    }
    
    public void setDetectionPlan(DetectionPlan detectionPlan) {
        this.detectionPlan = detectionPlan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddetectiontype", nullable=false)
    public DetectionType getDetectionType() {
        return this.detectionType;
    }
    
    public void setDetectionType(DetectionType detectionType) {
        this.detectionType = detectionType;
    }

    
    @Column(name="description", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="execution", length=29)
    public Date getExecution() {
        return this.execution;
    }
    
    public void setExecution(Date execution) {
        this.execution = execution;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="schedulefrom", length=29)
    public Date getSchedulefrom() {
        return this.schedulefrom;
    }
    
    public void setSchedulefrom(Date schedulefrom) {
        this.schedulefrom = schedulefrom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="scheduleto", length=29)
    public Date getScheduleto() {
        return this.scheduleto;
    }
    
    public void setScheduleto(Date scheduleto) {
        this.scheduleto = scheduleto;
    }

    
    @Column(name="completed")
    public Boolean getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    
    @Column(name="attachmenturl")
    public String getAttachmenturl() {
        return this.attachmenturl;
    }
    
    public void setAttachmenturl(String attachmenturl) {
        this.attachmenturl = attachmenturl;
    }

    
    @Column(name="mimetype")
    public String getMimetype() {
        return this.mimetype;
    }
    
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    
    @Column(name="filename")
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="comment")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="taskuuid", unique=true, nullable=false, length=36)
    public String getTaskuuid() {
        return this.taskuuid;
    }
    
    public void setTaskuuid(String taskuuid) {
        this.taskuuid = taskuuid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detectionTask")
    public Set<DetectionResult> getDetectionResults() {
        return this.detectionResults;
    }
    
    public void setDetectionResults(Set<DetectionResult> detectionResults) {
        this.detectionResults = detectionResults;
    }




}


