package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 20-apr-2017 6.54.04 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HealthDevicetype generated by hbm2java
 */
@Entity
@Table(name="tm_health_devicetype"
)
public class HealthDevicetype  implements java.io.Serializable {


     private Long idhealthdevicetype;
     private String modelname;
     private String attachmenturl;
     private String website;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<HealthDevice> healthDevices = new HashSet<HealthDevice>(0);

    public HealthDevicetype() {
    }

	
    public HealthDevicetype(Long idhealthdevicetype, Date created, Date updated, boolean active, String updateuser) {
        this.idhealthdevicetype = idhealthdevicetype;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public HealthDevicetype(Long idhealthdevicetype, String modelname, String attachmenturl, String website, Date created, Date updated, boolean active, String updateuser, Set<HealthDevice> healthDevices) {
       this.idhealthdevicetype = idhealthdevicetype;
       this.modelname = modelname;
       this.attachmenturl = attachmenturl;
       this.website = website;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.healthDevices = healthDevices;
    }
   
     @Id 

    
    @Column(name="idhealthdevicetype", unique=true, nullable=false)
    public Long getIdhealthdevicetype() {
        return this.idhealthdevicetype;
    }
    
    public void setIdhealthdevicetype(Long idhealthdevicetype) {
        this.idhealthdevicetype = idhealthdevicetype;
    }

    
    @Column(name="modelname", length=45)
    public String getModelname() {
        return this.modelname;
    }
    
    public void setModelname(String modelname) {
        this.modelname = modelname;
    }

    
    @Column(name="attachmenturl", length=45)
    public String getAttachmenturl() {
        return this.attachmenturl;
    }
    
    public void setAttachmenturl(String attachmenturl) {
        this.attachmenturl = attachmenturl;
    }

    
    @Column(name="website", length=45)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="healthDevicetype")
    public Set<HealthDevice> getHealthDevices() {
        return this.healthDevices;
    }
    
    public void setHealthDevices(Set<HealthDevice> healthDevices) {
        this.healthDevices = healthDevices;
    }




}


