package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 20-apr-2017 6.54.04 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientCaregiver generated by hbm2java
 */
@Entity
@Table(name="tm_patient_caregiver"
)
public class PatientCaregiver  implements java.io.Serializable {


     private PatientCaregiverId id;
     private CareGiver careGiver;
     private Patient patient;
     private String relationship;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;

    public PatientCaregiver() {
    }

    public PatientCaregiver(PatientCaregiverId id, CareGiver careGiver, Patient patient, String relationship, Date created, Date updated, boolean active, String updateuser) {
       this.id = id;
       this.careGiver = careGiver;
       this.patient = patient;
       this.relationship = relationship;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idpatient", column=@Column(name="idpatient", nullable=false) ), 
        @AttributeOverride(name="idcaregiver", column=@Column(name="idcaregiver", nullable=false) ) } )
    public PatientCaregiverId getId() {
        return this.id;
    }
    
    public void setId(PatientCaregiverId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcaregiver", nullable=false, insertable=false, updatable=false)
    public CareGiver getCareGiver() {
        return this.careGiver;
    }
    
    public void setCareGiver(CareGiver careGiver) {
        this.careGiver = careGiver;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpatient", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="relationship", nullable=false)
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }




}


