package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 20-apr-2017 6.54.04 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicianOrganizationunitId generated by hbm2java
 */
@Embeddable
public class PhysicianOrganizationunitId  implements java.io.Serializable {


     private Long idphysician;
     private Long idorganizationunit;

    public PhysicianOrganizationunitId() {
    }

    public PhysicianOrganizationunitId(Long idphysician, Long idorganizationunit) {
       this.idphysician = idphysician;
       this.idorganizationunit = idorganizationunit;
    }
   


    @Column(name="idphysician", nullable=false)
    public Long getIdphysician() {
        return this.idphysician;
    }
    
    public void setIdphysician(Long idphysician) {
        this.idphysician = idphysician;
    }


    @Column(name="idorganizationunit", nullable=false)
    public Long getIdorganizationunit() {
        return this.idorganizationunit;
    }
    
    public void setIdorganizationunit(Long idorganizationunit) {
        this.idorganizationunit = idorganizationunit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhysicianOrganizationunitId) ) return false;
		 PhysicianOrganizationunitId castOther = ( PhysicianOrganizationunitId ) other; 
         
		 return ( (this.getIdphysician()==castOther.getIdphysician()) || ( this.getIdphysician()!=null && castOther.getIdphysician()!=null && this.getIdphysician().equals(castOther.getIdphysician()) ) )
 && ( (this.getIdorganizationunit()==castOther.getIdorganizationunit()) || ( this.getIdorganizationunit()!=null && castOther.getIdorganizationunit()!=null && this.getIdorganizationunit().equals(castOther.getIdorganizationunit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdphysician() == null ? 0 : this.getIdphysician().hashCode() );
         result = 37 * result + ( getIdorganizationunit() == null ? 0 : this.getIdorganizationunit().hashCode() );
         return result;
   }   


}


