package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 11-apr-2017 13.43.21 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Physician generated by hbm2java
 */
@Entity
@Table(name="tm_physician"
)
public class Physician  implements java.io.Serializable {


     private Long idphysician;
     private String name;
     private String surname;
     private Character gender;
     private String telephone;
     private String skype;
     private String email;
     private Date dateofbirth;
     private String username;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<PhysicianOrganizationunit> physicianOrganizationunits = new HashSet<PhysicianOrganizationunit>(0);
     private Set<Message> messages = new HashSet<Message>(0);
     private Set<SpecialtyType> specialtyTypes = new HashSet<SpecialtyType>(0);
     private Set<PhysicianPatient> physicianPatients = new HashSet<PhysicianPatient>(0);
     private Set<MeetingRequest> meetingRequests = new HashSet<MeetingRequest>(0);

    public Physician() {
    }

	
    public Physician(Long idphysician, String username, Date created, Date updated, boolean active, String updateuser) {
        this.idphysician = idphysician;
        this.username = username;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public Physician(Long idphysician, String name, String surname, Character gender, String telephone, String skype, String email, Date dateofbirth, String username, Date created, Date updated, boolean active, String updateuser, Set<PhysicianOrganizationunit> physicianOrganizationunits, Set<Message> messages, Set<SpecialtyType> specialtyTypes, Set<PhysicianPatient> physicianPatients, Set<MeetingRequest> meetingRequests) {
       this.idphysician = idphysician;
       this.name = name;
       this.surname = surname;
       this.gender = gender;
       this.telephone = telephone;
       this.skype = skype;
       this.email = email;
       this.dateofbirth = dateofbirth;
       this.username = username;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.physicianOrganizationunits = physicianOrganizationunits;
       this.messages = messages;
       this.specialtyTypes = specialtyTypes;
       this.physicianPatients = physicianPatients;
       this.meetingRequests = meetingRequests;
    }
   
     @Id 

    
    @Column(name="idphysician", unique=true, nullable=false)
    public Long getIdphysician() {
        return this.idphysician;
    }
    
    public void setIdphysician(Long idphysician) {
        this.idphysician = idphysician;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="telephone", length=100)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="skype", length=100)
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateofbirth", length=13)
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physician")
    public Set<PhysicianOrganizationunit> getPhysicianOrganizationunits() {
        return this.physicianOrganizationunits;
    }
    
    public void setPhysicianOrganizationunits(Set<PhysicianOrganizationunit> physicianOrganizationunits) {
        this.physicianOrganizationunits = physicianOrganizationunits;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physician")
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="tm_physician_specialtytype", joinColumns = { 
        @JoinColumn(name="idphysician", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idspecialtytype", nullable=false, updatable=false) })
    public Set<SpecialtyType> getSpecialtyTypes() {
        return this.specialtyTypes;
    }
    
    public void setSpecialtyTypes(Set<SpecialtyType> specialtyTypes) {
        this.specialtyTypes = specialtyTypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physician")
    public Set<PhysicianPatient> getPhysicianPatients() {
        return this.physicianPatients;
    }
    
    public void setPhysicianPatients(Set<PhysicianPatient> physicianPatients) {
        this.physicianPatients = physicianPatients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="physician")
    public Set<MeetingRequest> getMeetingRequests() {
        return this.meetingRequests;
    }
    
    public void setMeetingRequests(Set<MeetingRequest> meetingRequests) {
        this.meetingRequests = meetingRequests;
    }




}


