package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 20-apr-2017 6.54.04 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="tm_region"
)
public class Region  implements java.io.Serializable {


     private Long idregion;
     private Country country;
     private String regionname;
     private String regionstdcode;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<Province> provinces = new HashSet<Province>(0);

    public Region() {
    }

	
    public Region(Long idregion, Country country, Date created, Date updated, boolean active, String updateuser) {
        this.idregion = idregion;
        this.country = country;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public Region(Long idregion, Country country, String regionname, String regionstdcode, Date created, Date updated, boolean active, String updateuser, Set<Province> provinces) {
       this.idregion = idregion;
       this.country = country;
       this.regionname = regionname;
       this.regionstdcode = regionstdcode;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.provinces = provinces;
    }
   
     @Id 

    
    @Column(name="idregion", unique=true, nullable=false)
    public Long getIdregion() {
        return this.idregion;
    }
    
    public void setIdregion(Long idregion) {
        this.idregion = idregion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcountry", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="regionname", length=100)
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    
    @Column(name="regionstdcode", length=10)
    public String getRegionstdcode() {
        return this.regionstdcode;
    }
    
    public void setRegionstdcode(String regionstdcode) {
        this.regionstdcode = regionstdcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Province> getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Set<Province> provinces) {
        this.provinces = provinces;
    }




}


