package it.clevercom.echo.hibernate.tm.postgresql.entity;
// Generated 11-apr-2017 13.43.21 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkList generated by hbm2java
 */
@Entity
@Table(name="tm_work_list"
)
public class WorkList  implements java.io.Serializable {


     private Long idworklist;
     private String username;
     private Date created;
     private Date updated;
     private boolean active;
     private String updateuser;
     private Set<WorkTask> workTasks = new HashSet<WorkTask>(0);

    public WorkList() {
    }

	
    public WorkList(Long idworklist, String username, Date created, Date updated, boolean active, String updateuser) {
        this.idworklist = idworklist;
        this.username = username;
        this.created = created;
        this.updated = updated;
        this.active = active;
        this.updateuser = updateuser;
    }
    public WorkList(Long idworklist, String username, Date created, Date updated, boolean active, String updateuser, Set<WorkTask> workTasks) {
       this.idworklist = idworklist;
       this.username = username;
       this.created = created;
       this.updated = updated;
       this.active = active;
       this.updateuser = updateuser;
       this.workTasks = workTasks;
    }
   
     @Id 

    
    @Column(name="idworklist", unique=true, nullable=false)
    public Long getIdworklist() {
        return this.idworklist;
    }
    
    public void setIdworklist(Long idworklist) {
        this.idworklist = idworklist;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="updateuser", nullable=false, length=100)
    public String getUpdateuser() {
        return this.updateuser;
    }
    
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="workList")
    public Set<WorkTask> getWorkTasks() {
        return this.workTasks;
    }
    
    public void setWorkTasks(Set<WorkTask> workTasks) {
        this.workTasks = workTasks;
    }




}


