package it.clevercom.echo.tm.model.entity;
// Generated 17-feb-2017 16.34.42 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetectiontypeMeasurementtypeId generated by hbm2java
 */
@Embeddable
public class DetectiontypeMeasurementtypeId implements java.io.Serializable {

	private long iddetectiontype;
	private long idmeasurementtype;

	public DetectiontypeMeasurementtypeId() {
	}

	public DetectiontypeMeasurementtypeId(long iddetectiontype, long idmeasurementtype) {
		this.iddetectiontype = iddetectiontype;
		this.idmeasurementtype = idmeasurementtype;
	}

	@Column(name = "iddetectiontype", nullable = false)
	public long getIddetectiontype() {
		return this.iddetectiontype;
	}

	public void setIddetectiontype(long iddetectiontype) {
		this.iddetectiontype = iddetectiontype;
	}

	@Column(name = "idmeasurementtype", unique = true, nullable = false)
	public long getIdmeasurementtype() {
		return this.idmeasurementtype;
	}

	public void setIdmeasurementtype(long idmeasurementtype) {
		this.idmeasurementtype = idmeasurementtype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetectiontypeMeasurementtypeId))
			return false;
		DetectiontypeMeasurementtypeId castOther = (DetectiontypeMeasurementtypeId) other;

		return (this.getIddetectiontype() == castOther.getIddetectiontype())
				&& (this.getIdmeasurementtype() == castOther.getIdmeasurementtype());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIddetectiontype();
		result = 37 * result + (int) this.getIdmeasurementtype();
		return result;
	}

}
