package it.clevercom.echo.tm.model.entity;
// Generated 17-feb-2017 16.34.42 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhysicianOrganizationunitId generated by hbm2java
 */
@Embeddable
public class PhysicianOrganizationunitId implements java.io.Serializable {

	private long idphysician;
	private long idorganizationunit;

	public PhysicianOrganizationunitId() {
	}

	public PhysicianOrganizationunitId(long idphysician, long idorganizationunit) {
		this.idphysician = idphysician;
		this.idorganizationunit = idorganizationunit;
	}

	@Column(name = "idphysician", nullable = false)
	public long getIdphysician() {
		return this.idphysician;
	}

	public void setIdphysician(long idphysician) {
		this.idphysician = idphysician;
	}

	@Column(name = "idorganizationunit", nullable = false)
	public long getIdorganizationunit() {
		return this.idorganizationunit;
	}

	public void setIdorganizationunit(long idorganizationunit) {
		this.idorganizationunit = idorganizationunit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhysicianOrganizationunitId))
			return false;
		PhysicianOrganizationunitId castOther = (PhysicianOrganizationunitId) other;

		return (this.getIdphysician() == castOther.getIdphysician())
				&& (this.getIdorganizationunit() == castOther.getIdorganizationunit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdphysician();
		result = 37 * result + (int) this.getIdorganizationunit();
		return result;
	}

}
