package it.clevercom.echo.sso.model.entity;
// Generated 15-feb-2017 17.21.43 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "LOGIN", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class Login implements java.io.Serializable {

	private long idlogin;
	private String username;
	private String password;
	private String email;
	private Serializable lastpasswordreset;
	private Boolean adlogon;
	private Serializable created;
	private Serializable updated;
	private boolean active;
	private String updateuser;
	private Set<LoginApplication> loginApplications = new HashSet<LoginApplication>(0);

	public Login() {
	}

	public Login(long idlogin, String username, String password, String email, Serializable lastpasswordreset,
			Serializable created, Serializable updated, boolean active, String updateuser) {
		this.idlogin = idlogin;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastpasswordreset = lastpasswordreset;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateuser = updateuser;
	}

	public Login(long idlogin, String username, String password, String email, Serializable lastpasswordreset,
			Boolean adlogon, Serializable created, Serializable updated, boolean active, String updateuser,
			Set<LoginApplication> loginApplications) {
		this.idlogin = idlogin;
		this.username = username;
		this.password = password;
		this.email = email;
		this.lastpasswordreset = lastpasswordreset;
		this.adlogon = adlogon;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateuser = updateuser;
		this.loginApplications = loginApplications;
	}

	@Id

	@Column(name = "IDLOGIN", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdlogin() {
		return this.idlogin;
	}

	public void setIdlogin(long idlogin) {
		this.idlogin = idlogin;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "LASTPASSWORDRESET", nullable = false)
	public Serializable getLastpasswordreset() {
		return this.lastpasswordreset;
	}

	public void setLastpasswordreset(Serializable lastpasswordreset) {
		this.lastpasswordreset = lastpasswordreset;
	}

	@Column(name = "ADLOGON", precision = 1, scale = 0)
	public Boolean getAdlogon() {
		return this.adlogon;
	}

	public void setAdlogon(Boolean adlogon) {
		this.adlogon = adlogon;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "UPDATEUSER", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "login")
	public Set<LoginApplication> getLoginApplications() {
		return this.loginApplications;
	}

	public void setLoginApplications(Set<LoginApplication> loginApplications) {
		this.loginApplications = loginApplications;
	}

}
