package it.clevercom.echo.sso.model.entity;
// Generated 15-feb-2017 17.21.43 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoginApplication generated by hbm2java
 */
@Entity
@Table(name = "LOGIN_APPLICATION")
public class LoginApplication implements java.io.Serializable {

	private LoginApplicationId id;
	private Application application;
	private Login login;
	private String authorities;
	private Serializable created;
	private Serializable updated;
	private boolean active;
	private String updateuser;

	public LoginApplication() {
	}

	public LoginApplication(LoginApplicationId id, Application application, Login login, String authorities,
			Serializable created, Serializable updated, boolean active, String updateuser) {
		this.id = id;
		this.application = application;
		this.login = login;
		this.authorities = authorities;
		this.created = created;
		this.updated = updated;
		this.active = active;
		this.updateuser = updateuser;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "applicationIdapplication", column = @Column(name = "APPLICATION_IDAPPLICATION", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "loginIdlogin", column = @Column(name = "LOGIN_IDLOGIN", nullable = false, precision = 10, scale = 0)) })
	public LoginApplicationId getId() {
		return this.id;
	}

	public void setId(LoginApplicationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLICATION_IDAPPLICATION", nullable = false, insertable = false, updatable = false)
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGIN_IDLOGIN", nullable = false, insertable = false, updatable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "AUTHORITIES", nullable = false, length = 4000)
	public String getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(String authorities) {
		this.authorities = authorities;
	}

	@Column(name = "CREATED", nullable = false)
	public Serializable getCreated() {
		return this.created;
	}

	public void setCreated(Serializable created) {
		this.created = created;
	}

	@Column(name = "UPDATED", nullable = false)
	public Serializable getUpdated() {
		return this.updated;
	}

	public void setUpdated(Serializable updated) {
		this.updated = updated;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "UPDATEUSER", nullable = false, length = 100)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

}
