package it.clevercom.echo.hibernate.rd.postgresql.entity;
// Generated 19-apr-2017 15.19.48 by Hibernate Tools 5.2.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ModalityService generated by hbm2java
 */
@Entity
@Table(name="rd_modality_service"
    , uniqueConstraints = @UniqueConstraint(columnNames={"idmodality", "idservice"}) 
)
public class ModalityService  implements java.io.Serializable {


     private Long idmodalityservice;
     private Modality modality;
     private Service service;

    public ModalityService() {
    }

    public ModalityService(Modality modality, Service service) {
       this.modality = modality;
       this.service = service;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="modalityservice_idmodalityservice_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idmodalityservice", unique=true, nullable=false)
    public Long getIdmodalityservice() {
        return this.idmodalityservice;
    }
    
    public void setIdmodalityservice(Long idmodalityservice) {
        this.idmodalityservice = idmodalityservice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmodality", nullable=false)
    public Modality getModality() {
        return this.modality;
    }
    
    public void setModality(Modality modality) {
        this.modality = modality;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservice", nullable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }




}


