package it.clevercom.echo.hibernate.rd.postgresql.entity;
// Generated 5-apr-2017 11.35.01 by Hibernate Tools 5.2.2.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ModalityDailyAllocation generated by hbm2java
 */
@Entity
@Table(name="rd_modality_daily_allocation"
    , uniqueConstraints = @UniqueConstraint(columnNames={"idmodality", "day"}) 
)
public class ModalityDailyAllocation  implements java.io.Serializable {


     private Long idmodalitydailyallocation;
     private Modality modality;
     private Date day;
     private Integer allocation;
     private Date created;
     private Date updated;
     private String userupdate;
     private Boolean active;
     private Integer excess;

    public ModalityDailyAllocation() {
    }

	
    public ModalityDailyAllocation(Date created, Date updated, String userupdate, Boolean active) {
        this.created = created;
        this.updated = updated;
        this.userupdate = userupdate;
        this.active = active;
    }
    public ModalityDailyAllocation(Modality modality, Date day, Integer allocation, Date created, Date updated, String userupdate, Boolean active, Integer excess) {
       this.modality = modality;
       this.day = day;
       this.allocation = allocation;
       this.created = created;
       this.updated = updated;
       this.userupdate = userupdate;
       this.active = active;
       this.excess = excess;
    }
   
     @GenericGenerator(name="generator", strategy="org.hibernate.id.enhanced.SequenceStyleGenerator", parameters={@Parameter(name="optimizer", value="none"), @Parameter(name="sequence_name", value="modalitydailyallocation_idmodalitydailyallocation_seq"), @Parameter(name="increment_size", value="1")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="idmodalitydailyallocation", unique=true, nullable=false)
    public Long getIdmodalitydailyallocation() {
        return this.idmodalitydailyallocation;
    }
    
    public void setIdmodalitydailyallocation(Long idmodalitydailyallocation) {
        this.idmodalitydailyallocation = idmodalitydailyallocation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmodality")
    public Modality getModality() {
        return this.modality;
    }
    
    public void setModality(Modality modality) {
        this.modality = modality;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="day", length=13)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }

    
    @Column(name="allocation")
    public Integer getAllocation() {
        return this.allocation;
    }
    
    public void setAllocation(Integer allocation) {
        this.allocation = allocation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=29)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=29)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    
    @Column(name="userupdate", nullable=false, length=100)
    public String getUserupdate() {
        return this.userupdate;
    }
    
    public void setUserupdate(String userupdate) {
        this.userupdate = userupdate;
    }

    
    @Column(name="active", nullable=false)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    
    @Column(name="excess")
    public Integer getExcess() {
        return this.excess;
    }
    
    public void setExcess(Integer excess) {
        this.excess = excess;
    }




}


